# Welcome to EMS Documents
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EvoStream Media Server
index_title: Back to Index
home_title: Back to EvoStream.com
home_url: "https://evostream.com"
email_name: Administrator
email: admin@evostream.com
description: > # this means to ignore newlines until "baseurl:"
  EvoStream, 1010 Turquoise, Suite 101,
  San Diego, CA 92109, California, USA.
baseurl: "/sample_content"
url: "http://docs.evostream.com"
#baseurl: "" # for local test only
#url: "http://localhost:4000" # for local test only
twitter_username: EvoStreamInc
github_username:  EvoStream

# Build settings
markdown: kramdown
